# 计算设备

用torch.cuda.is_available()查看GPU是否可用

In [1]:
import torch
from torch import nn

torch.cuda.is_available()

True

In [2]:
# 查看GPU数量
torch.cuda.device_count()

1

In [3]:
# 查看当前GPU索引号，索引号从0开始
torch.cuda.current_device()

0

In [4]:
# 根据索引号查看GPU名字
torch.cuda.get_device_name(0)

'GeForce GTX 1060 6GB'

# Tensor的GPU计算

默认情况，Tensor会被保存在内存上。之前每次打印Tensor的时候看不到GPU相关标识

In [5]:
x = torch.tensor([1, 2, 3])
x

tensor([1, 2, 3])

使用.cuda()可以将CPU上的Tensor复制到GPU上。多块GPU使用.cuda(i)

cuda(0)和cuda()等价

In [6]:
x = x.cuda(0)
x

tensor([1, 2, 3], device='cuda:0')

In [7]:
x.device

device(type='cuda', index=0)

In [8]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

x = torch.tensor([1, 2, 3], device=device)
x = torch.tensor([1, 2, 3]).to(device)
x

tensor([1, 2, 3], device='cuda:0')

存储在不同位置中的数据不可以直接进行计算。不同GPU，CPU和GPU之间不可

# 模型的GPU计算

同Tensor类似，Pytorch模型也可以通过.cuda转换到GPU上。

In [9]:
net = nn.Linear(3, 1)
list(net.parameters())[0].device

device(type='cpu')

In [10]:
net.cuda()
list(net.parameters())[0].device

device(type='cuda', index=0)