# PyTorch Tensor

## 1 创建Tensor
创建未初始化的Tensor

In [1]:
import torch

x = torch.empty(5, 3)
print(x)

tensor([[9.5511e-39, 1.0102e-38, 5.0510e-39],
        [9.9184e-39, 9.0000e-39, 1.0561e-38],
        [1.0653e-38, 4.1327e-39, 8.9082e-39],
        [9.8265e-39, 9.4592e-39, 1.0561e-38],
        [1.0653e-38, 1.0469e-38, 9.5510e-39]])


创建随机初始化的Tensor

In [2]:
x = torch.rand(5, 3)
print(x)

tensor([[0.0291, 0.8185, 0.8755],
        [0.1553, 0.3267, 0.2336],
        [0.7914, 0.8781, 0.3882],
        [0.8944, 0.4507, 0.4869],
        [0.9340, 0.1866, 0.5516]])


创建long型全0的Tensor

In [3]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


直接根据数据创建

In [4]:
x = torch.tensor([4, 4, 5.6, 3])
print(x)

tensor([4.0000, 4.0000, 5.6000, 3.0000])


获取形状

返回的torch.size是一个tuple, 支持所有tuple操作

In [5]:
print(x.size())
print(x.shape)

torch.Size([4])
torch.Size([4])


## 2 操作

### 2.1 算术

In [6]:
x = torch.ones(5, 3)
y = torch.rand(5, 3)
print(x)
print(y)
print(x + y)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.5436, 0.3165, 0.1776],
        [0.3701, 0.9432, 0.6293],
        [0.2464, 0.3108, 0.4058],
        [0.4147, 0.5825, 0.1632],
        [0.9204, 0.6774, 0.9400]])
tensor([[1.5436, 1.3165, 1.1776],
        [1.3701, 1.9432, 1.6293],
        [1.2464, 1.3108, 1.4058],
        [1.4147, 1.5825, 1.1632],
        [1.9204, 1.6774, 1.9400]])


In [7]:
print(torch.add(x, y))

tensor([[1.5436, 1.3165, 1.1776],
        [1.3701, 1.9432, 1.6293],
        [1.2464, 1.3108, 1.4058],
        [1.4147, 1.5825, 1.1632],
        [1.9204, 1.6774, 1.9400]])


In [8]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[1.5436, 1.3165, 1.1776],
        [1.3701, 1.9432, 1.6293],
        [1.2464, 1.3108, 1.4058],
        [1.4147, 1.5825, 1.1632],
        [1.9204, 1.6774, 1.9400]])


In [9]:
y.add_(x)
print(y)

tensor([[1.5436, 1.3165, 1.1776],
        [1.3701, 1.9432, 1.6293],
        [1.2464, 1.3108, 1.4058],
        [1.4147, 1.5825, 1.1632],
        [1.9204, 1.6774, 1.9400]])


### 2.2 索引

索引出来的结果与原数据共享内存，也即修改一个，另一个会跟着修改

In [10]:
y = x[0, :]
y += 1
print(y)
print(x[0, :])

tensor([2., 2., 2.])
tensor([2., 2., 2.])


### 2.3 改变形状

In [11]:
y = x.view(15)
z = x.view(-1, 5)
print(x.size(), y.size(), z.size())

torch.Size([5, 3]) torch.Size([15]) torch.Size([3, 5])


In [12]:
x += 1
print(x)
print(y)

tensor([[3., 3., 3.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])
tensor([3., 3., 3., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])


创造副本

In [13]:
x_cp = x.clone().view(15)
x -= 1
print(x)
print(x_cp)

tensor([[2., 2., 2.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([3., 3., 3., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])


item(), 将一个标量Tensor转换成Python number

In [14]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.6288])
0.6287678480148315


### 2.3 广播机制

In [16]:
x = torch.arange(1, 3).view(1, 2)
print(x)
y = torch.arange(1, 4).view(3, 1)
print(y)
print(x+y)

tensor([[1, 2]])
tensor([[1],
        [2],
        [3]])
tensor([[2, 3],
        [3, 4],
        [4, 5]])


### 2.4 内存开销

In [17]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
y = y+x
print(id(y) == id_before)

False


In [18]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
y[:] = y+x
print(id(y) == id_before)

True


In [19]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
torch.add(x, y, out = y)
print(id(y) == id_before)

True


### 2.5 tensor和numpy相互转换

numpy()和from_numpy()将tensor和numpy中的数组相互转换。这两个函数所产生的tensor和numpy中的数组共享相同的内存

tensor转numpy

In [20]:
a = torch.ones(5)
b = a.numpy()
print(a, b)

a += 1
print(a, b)
b += 1
print(a, b)

tensor([1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]
tensor([3., 3., 3., 3., 3.]) [3. 3. 3. 3. 3.]


numpy转tensor

In [21]:
import numpy as np

a = np.ones(5)
b = torch.from_numpy(a)
print(a, b)

a += 1
print(a, b)
b += 1
print(a, b)

[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[3. 3. 3. 3. 3.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


In [22]:
c = torch.tensor(a) #进行数据拷贝，不共享内存
a += 1
print(a, c)

[4. 4. 4. 4. 4.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


### 2.6 tensor on GPU

用方法to()可以将Tensor在CPU和GPU之间相互移动

In [23]:


if torch.cuda.is_available():
    device = torch.device("cuda") # GPU
    y = torch.ones_like(x, device=device) # 直接创建一个在GPU上的Tensor
    x = x.to(device) # 等价于 .to("cuda")
    z = x+y
    print(z)
    print(z.to("cpu", torch.double)) # to()还可以同时更改数据类型

tensor([2, 3], device='cuda:0')
tensor([2., 3.], dtype=torch.float64)


## 3 自动求梯度

### 3.1 tensor设置

In [24]:
x = torch.ones(2, 2, requires_grad = True)
print(x)
print(x.grad_fn)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
None


In [25]:
y = x + 2
print(y)
print(y.grad_fn)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [26]:
print(x.is_leaf, y.is_leaf)

True False


In [27]:
z = y * y * 3
out = z.mean()
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


### 3.2 梯度

In [28]:
out.backward()
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


PS : grad在反向传播过程中是累加的(accumulated), 意味着每一次运行反向传播, 梯度都会累加之前的梯度，所以一般在反向传播之前需把梯度清零。

In [30]:
out2 = x.sum()
out2.backward()
print(x.grad)

out3 = x.sum()
x.grad.data.zero_()
out3.backward()
print(x.grad)

tensor([[5.5000, 5.5000],
        [5.5000, 5.5000]])
tensor([[1., 1.],
        [1., 1.]])


In [32]:
x = torch.tensor([1.0, 2.0, 3.0, 4.0], requires_grad = True)
y = 2 * x
z = y.view(2, 2)
print(z)


tensor([[2., 4.],
        [6., 8.]], grad_fn=<ViewBackward>)


y不是一个标量，调用backward时需要传入一个和y同形的权重向量进行加权求和得到一个标量

In [33]:
v = torch.tensor([[1.0, 0.1], [0.01, 0.001]], dtype = torch.float)
z.backward(v)
print(x.grad)

tensor([2.0000, 0.2000, 0.0200, 0.0020])


中断梯度追踪的例子

In [34]:
x = torch.tensor(1.0, requires_grad = True)
y1 = x ** 2
with torch.no_grad():
    y2 = x ** 3
y3 = y1 + y2

print(x.requires_grad)
print(y1, y1.requires_grad)
print(y2, y2.requires_grad)
print(y3, y3.requires_grad)

True
tensor(1., grad_fn=<PowBackward0>) True
tensor(1.) False
tensor(2., grad_fn=<AddBackward0>) True


In [35]:
y3.backward()
print(x.grad)

tensor(2.)
